trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSource: 'spec'
    versionSpec: '10.x'
- script: 'npm install'
- task: oc-cmd@3
  inputs:
    connectionType: 'OpenShift Connection Service'
    openshiftService: 'VSTS example'
    version: '4.2'
    cmd: 'oc start-build webhooktesti --follow'
- task: oc-cmd@3
  inputs:
    connectionType: 'OpenShift Connection Service'
    openshiftService: 'VSTS example'
    version: '4.2'
    cmd: 'oc status'